/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_alternativetags.c"
#include "bar_dwmblocks.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statusbutton.c"
#include "bar_statuscmd.c"
#include "bar_tabgroups.c"
#include "bar_tags.c"
#include "bar_taggrid.c"
#include "bar_wintitle.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"
#include "bar_layoutmenu.c"

/* Other patches */
#include "attachx.c"
#include "autostart.c"
#include "recttoclient.c"
#include "cfacts.c"
#include "focusadjacenttag.c"
#include "focusfollowmouse.c"
#include "ipc.c"
#ifdef VERSION
#include "ipc/IPCClient.c"
#include "ipc/yajl_dumps.c"
#include "ipc/ipc.c"
#include "ipc/util.c"
#endif
#include "movecenter.c"
#include "movestack.c"
#include "nametag.c"
#include "pertag.c"
#include "placemouse.c"
#include "restartsig.c"
#include "rotatestack.c"
#include "roundedcorners.c"
#include "scratchpad.c"
#include "setborderpx.c"
#include "shift.c"
#include "shifttag.c"
#include "shiftview.c"
#include "swallow.c"
#include "vanitygaps.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_bstackhoriz.c"
#include "layout_centeredmaster.c"
#include "layout_centeredfloatingmaster.c"
#include "layout_columns.c"
#include "layout_deck.c"
#include "layout_fibonacci.c"
#include "layout_gapplessgrid.c"
#include "layout_grid.c"
#include "layout_horizgrid.c"
#include "layout_monocle.c"
#include "layout_tile.c"

