/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alternativetags.h"
#include "bar_dwmblocks.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statusbutton.h"
#include "bar_statuscmd.h"
#include "bar_tabgroups.h"
#include "bar_tags.h"
#include "bar_taggrid.h"
#include "bar_wintitle.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"
#include "bar_layoutmenu.h"

/* Other patches */
#include "attachx.h"
#include "autostart.h"
#include "recttoclient.h"
#include "cfacts.h"
#include "focusadjacenttag.h"
#include "focusfollowmouse.h"
#include "ipc.h"
#include "ipc/ipc.h"
#include "ipc/util.h"
#include "movecenter.h"
#include "movestack.h"
#include "nametag.h"
#include "pertag.h"
#include "placemouse.h"
#include "restartsig.h"
#include "rotatestack.h"
#include "roundedcorners.h"
#include "scratchpad.h"
#include "setborderpx.h"
#include "shift.h"
#include "shifttag.h"
#include "shiftview.h"
#include "swallow.h"
#include "vanitygaps.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_bstackhoriz.h"
#include "layout_centeredmaster.h"
#include "layout_centeredfloatingmaster.h"
#include "layout_columns.h"
#include "layout_deck.h"
#include "layout_fibonacci.h"
#include "layout_gapplessgrid.h"
#include "layout_grid.h"
#include "layout_horizgrid.h"
#include "layout_monocle.h"
#include "layout_tile.h"

