general {
    lock_cmd = pidof hyprlock || hyprlock        # Verhindert mehrere Instanzen von hyprlock
    # unlock_cmd = notify-send "unlock!"
    before_sleep_cmd = loginctl lock-session     # Sperrt den Bildschirm, falls das System schläft
    after_sleep_cmd = hyprctl dispatch dpms on   # Aktiviert den Monitor nach dem Aufwachen sofort wieder
    # ignore_dbus_inhibit = false
}

# Screen_lock (Aktiviert den Sperrbildschirm nach 10 Minuten)
listener {
    timeout = 600
    on-timeout = hyprctl switchxkblayout logitech-wireless-keyboard-pid:0068 && loginctl lock-session
    on-resume = sleep 1; notify-send "Welcome back to Hyprland  "
}
